server:
  port: 8080

logging:
  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          #google:
          #  client-id: <your client id>
          #  client-secret: <your client secret>

          #facebook:
          #  client-id: <your client id>
          #  client-secret: <your client secret>

          sgi-oidc:
            provider: spring
            client-id: sgi-oidc
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: "SGI Connect"
          sgi-client-authorization-code:
            provider: spring
            client-id: sgi-oidc
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: sgi-client-authorization-code
          sgi-oidc-client-credentials:
            provider: spring
            client-id: sgi-oidc
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: sgi-oidc-client-credentials
        provider:
          spring:
            issuer-uri: http://103.139.192.249:9000

messages:
  base-uri: http://103.171.84.244:8090/messages
